{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "Install and load all dependencies (first time only) \\\n",
        "NOTE: you may need to restart the runtime afterwards (CTRL+M .)."
      ],
      "metadata": {
        "id": "Siz3Hiq1JUZ1"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/PolitoVandal/project-sim2real-rialti-giunti-gjinaj/blob/main/colab_template/test_random_policy.ipynb)"
      ],
      "metadata": {
        "id": "h9EafyX8NLlA"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "!rm -rf \"project-sim2real-rialti-giunti-gjinaj\"  # Cancella la cartella e il suo contenuto usando il comando !rm\n",
        "!rm -rf \"sim2real\"  # Cancella la cartella e il suo contenuto usando il comando !rm\n",
        "!git clone https://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@github.com/PolitoVandal/project-sim2real-rialti-giunti-gjinaj"
      ],
      "metadata": {
        "id": "UG4ZM2KG_SLS",
        "outputId": "ea759116-84e8-4a0e-b83a-8d578888ca02",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "execution_count": 3,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Cloning into 'project-sim2real-rialti-giunti-gjinaj'...\n",
            "remote: Enumerating objects: 139, done.\u001b[K\n",
            "remote: Counting objects: 100% (113/113), done.\u001b[K\n",
            "remote: Compressing objects: 100% (82/82), done.\u001b[K\n",
            "remote: Total 139 (delta 62), reused 72 (delta 31), pack-reused 26 (from 1)\u001b[K\n",
            "Receiving objects: 100% (139/139), 948.72 KiB | 6.83 MiB/s, done.\n",
            "Resolving deltas: 100% (70/70), done.\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "import warnings\n",
        "\n",
        "if not os.path.exists('sim2real/models'):\n",
        "    os.makedirs('sim2real/models')\n",
        "\n",
        "if not os.path.exists('sim2real/plots'):\n",
        "    os.makedirs('sim2real/plots')"
      ],
      "metadata": {
        "id": "QUOzFdnmHzO7"
      },
      "execution_count": 4,
      "outputs": []
    },
    {
      "cell_type": "code",
      "execution_count": 5,
      "metadata": {
        "id": "AW6XT0jSJI8e",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "299f5e73-3106-4924-ba8b-3f150d7b3cf3"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Reading package lists... Done\n",
            "Building dependency tree... Done\n",
            "Reading state information... Done\n",
            "software-properties-common is already the newest version (0.99.22.9).\n",
            "The following additional packages will be installed:\n",
            "  libegl-dev libgl-dev libgles-dev libgles1 libglu1-mesa libglu1-mesa-dev libglvnd-core-dev\n",
            "  libglvnd-dev libglx-dev libopengl-dev libosmesa6\n",
            "The following NEW packages will be installed:\n",
            "  libegl-dev libgl-dev libgl1-mesa-dev libgl1-mesa-glx libgles-dev libgles1 libglew-dev\n",
            "  libglu1-mesa libglu1-mesa-dev libglvnd-core-dev libglvnd-dev libglx-dev libopengl-dev libosmesa6\n",
            "  libosmesa6-dev\n",
            "0 upgraded, 15 newly installed, 0 to remove and 49 not upgraded.\n",
            "Need to get 4,013 kB of archives.\n",
            "After this operation, 19.4 MB of additional disk space will be used.\n",
            "Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libglx-dev amd64 1.4.0-1 [14.1 kB]\n",
            "Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgl-dev amd64 1.4.0-1 [101 kB]\n",
            "Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 libegl-dev amd64 1.4.0-1 [18.0 kB]\n",
            "Get:4 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libgl1-mesa-glx amd64 23.0.4-0ubuntu1~22.04.1 [5,584 B]\n",
            "Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgles1 amd64 1.4.0-1 [11.5 kB]\n",
            "Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgles-dev amd64 1.4.0-1 [49.4 kB]\n",
            "Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libglvnd-core-dev amd64 1.4.0-1 [12.7 kB]\n",
            "Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libopengl-dev amd64 1.4.0-1 [3,400 B]\n",
            "Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libglvnd-dev amd64 1.4.0-1 [3,162 B]\n",
            "Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgl1-mesa-dev amd64 23.2.1-1ubuntu3.1~22.04.3 [6,848 B]\n",
            "Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 libglu1-mesa amd64 9.0.2-1 [145 kB]\n",
            "Get:12 http://archive.ubuntu.com/ubuntu jammy/main amd64 libglu1-mesa-dev amd64 9.0.2-1 [231 kB]\n",
            "Get:13 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libglew-dev amd64 2.2.0-4 [287 kB]\n",
            "Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libosmesa6 amd64 23.2.1-1ubuntu3.1~22.04.3 [3,115 kB]\n",
            "Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libosmesa6-dev amd64 23.2.1-1ubuntu3.1~22.04.3 [8,984 B]\n",
            "Fetched 4,013 kB in 1s (3,327 kB/s)\n",
            "Selecting previously unselected package libglx-dev:amd64.\n",
            "(Reading database ... 123638 files and directories currently installed.)\n",
            "Preparing to unpack .../00-libglx-dev_1.4.0-1_amd64.deb ...\n",
            "Unpacking libglx-dev:amd64 (1.4.0-1) ...\n",
            "Selecting previously unselected package libgl-dev:amd64.\n",
            "Preparing to unpack .../01-libgl-dev_1.4.0-1_amd64.deb ...\n",
            "Unpacking libgl-dev:amd64 (1.4.0-1) ...\n",
            "Selecting previously unselected package libegl-dev:amd64.\n",
            "Preparing to unpack .../02-libegl-dev_1.4.0-1_amd64.deb ...\n",
            "Unpacking libegl-dev:amd64 (1.4.0-1) ...\n",
            "Selecting previously unselected package libgl1-mesa-glx:amd64.\n",
            "Preparing to unpack .../03-libgl1-mesa-glx_23.0.4-0ubuntu1~22.04.1_amd64.deb ...\n",
            "Unpacking libgl1-mesa-glx:amd64 (23.0.4-0ubuntu1~22.04.1) ...\n",
            "Selecting previously unselected package libgles1:amd64.\n",
            "Preparing to unpack .../04-libgles1_1.4.0-1_amd64.deb ...\n",
            "Unpacking libgles1:amd64 (1.4.0-1) ...\n",
            "Selecting previously unselected package libgles-dev:amd64.\n",
            "Preparing to unpack .../05-libgles-dev_1.4.0-1_amd64.deb ...\n",
            "Unpacking libgles-dev:amd64 (1.4.0-1) ...\n",
            "Selecting previously unselected package libglvnd-core-dev:amd64.\n",
            "Preparing to unpack .../06-libglvnd-core-dev_1.4.0-1_amd64.deb ...\n",
            "Unpacking libglvnd-core-dev:amd64 (1.4.0-1) ...\n",
            "Selecting previously unselected package libopengl-dev:amd64.\n",
            "Preparing to unpack .../07-libopengl-dev_1.4.0-1_amd64.deb ...\n",
            "Unpacking libopengl-dev:amd64 (1.4.0-1) ...\n",
            "Selecting previously unselected package libglvnd-dev:amd64.\n",
            "Preparing to unpack .../08-libglvnd-dev_1.4.0-1_amd64.deb ...\n",
            "Unpacking libglvnd-dev:amd64 (1.4.0-1) ...\n",
            "Selecting previously unselected package libgl1-mesa-dev:amd64.\n",
            "Preparing to unpack .../09-libgl1-mesa-dev_23.2.1-1ubuntu3.1~22.04.3_amd64.deb ...\n",
            "Unpacking libgl1-mesa-dev:amd64 (23.2.1-1ubuntu3.1~22.04.3) ...\n",
            "Selecting previously unselected package libglu1-mesa:amd64.\n",
            "Preparing to unpack .../10-libglu1-mesa_9.0.2-1_amd64.deb ...\n",
            "Unpacking libglu1-mesa:amd64 (9.0.2-1) ...\n",
            "Selecting previously unselected package libglu1-mesa-dev:amd64.\n",
            "Preparing to unpack .../11-libglu1-mesa-dev_9.0.2-1_amd64.deb ...\n",
            "Unpacking libglu1-mesa-dev:amd64 (9.0.2-1) ...\n",
            "Selecting previously unselected package libglew-dev:amd64.\n",
            "Preparing to unpack .../12-libglew-dev_2.2.0-4_amd64.deb ...\n",
            "Unpacking libglew-dev:amd64 (2.2.0-4) ...\n",
            "Selecting previously unselected package libosmesa6:amd64.\n",
            "Preparing to unpack .../13-libosmesa6_23.2.1-1ubuntu3.1~22.04.3_amd64.deb ...\n",
            "Unpacking libosmesa6:amd64 (23.2.1-1ubuntu3.1~22.04.3) ...\n",
            "Selecting previously unselected package libosmesa6-dev:amd64.\n",
            "Preparing to unpack .../14-libosmesa6-dev_23.2.1-1ubuntu3.1~22.04.3_amd64.deb ...\n",
            "Unpacking libosmesa6-dev:amd64 (23.2.1-1ubuntu3.1~22.04.3) ...\n",
            "Setting up libglvnd-core-dev:amd64 (1.4.0-1) ...\n",
            "Setting up libgles1:amd64 (1.4.0-1) ...\n",
            "Setting up libgl1-mesa-glx:amd64 (23.0.4-0ubuntu1~22.04.1) ...\n",
            "Setting up libglx-dev:amd64 (1.4.0-1) ...\n",
            "Setting up libglu1-mesa:amd64 (9.0.2-1) ...\n",
            "Setting up libopengl-dev:amd64 (1.4.0-1) ...\n",
            "Setting up libgl-dev:amd64 (1.4.0-1) ...\n",
            "Setting up libosmesa6:amd64 (23.2.1-1ubuntu3.1~22.04.3) ...\n",
            "Setting up libegl-dev:amd64 (1.4.0-1) ...\n",
            "Setting up libglu1-mesa-dev:amd64 (9.0.2-1) ...\n",
            "Setting up libosmesa6-dev:amd64 (23.2.1-1ubuntu3.1~22.04.3) ...\n",
            "Setting up libgles-dev:amd64 (1.4.0-1) ...\n",
            "Setting up libglvnd-dev:amd64 (1.4.0-1) ...\n",
            "Setting up libglew-dev:amd64 (2.2.0-4) ...\n",
            "Setting up libgl1-mesa-dev:amd64 (23.2.1-1ubuntu3.1~22.04.3) ...\n",
            "Processing triggers for libc-bin (2.35-0ubuntu3.4) ...\n",
            "/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libumf.so.0 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link\n",
            "\n",
            "Reading package lists... Done\n",
            "Building dependency tree... Done\n",
            "Reading state information... Done\n",
            "patchelf is already the newest version (0.14.3-1).\n",
            "0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.\n",
            "Requirement already satisfied: gym in /usr/local/lib/python3.10/dist-packages (0.25.2)\n",
            "Requirement already satisfied: numpy>=1.18.0 in /usr/local/lib/python3.10/dist-packages (from gym) (1.26.4)\n",
            "Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from gym) (3.1.0)\n",
            "Requirement already satisfied: gym_notices>=0.0.4 in /usr/local/lib/python3.10/dist-packages (from gym) (0.0.8)\n",
            "Requirement already satisfied: free-mujoco-py in /usr/local/lib/python3.10/dist-packages (2.1.6)\n",
            "Requirement already satisfied: Cython<0.30.0,>=0.29.24 in /usr/local/lib/python3.10/dist-packages (from free-mujoco-py) (0.29.37)\n",
            "Requirement already satisfied: cffi<2.0.0,>=1.15.0 in /usr/local/lib/python3.10/dist-packages (from free-mujoco-py) (1.17.1)\n",
            "Requirement already satisfied: fasteners==0.15 in /usr/local/lib/python3.10/dist-packages (from free-mujoco-py) (0.15)\n",
            "Requirement already satisfied: glfw<2.0.0,>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from free-mujoco-py) (1.12.0)\n",
            "Requirement already satisfied: imageio<3.0.0,>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from free-mujoco-py) (2.36.1)\n",
            "Requirement already satisfied: numpy<2.0.0,>=1.21.3 in /usr/local/lib/python3.10/dist-packages (from free-mujoco-py) (1.26.4)\n",
            "Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from fasteners==0.15->free-mujoco-py) (1.17.0)\n",
            "Requirement already satisfied: monotonic>=0.1 in /usr/local/lib/python3.10/dist-packages (from fasteners==0.15->free-mujoco-py) (1.6)\n",
            "Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi<2.0.0,>=1.15.0->free-mujoco-py) (2.22)\n",
            "Requirement already satisfied: pillow>=8.3.2 in /usr/local/lib/python3.10/dist-packages (from imageio<3.0.0,>=2.9.0->free-mujoco-py) (11.1.0)\n",
            "Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.10/dist-packages (8.5.0)\n",
            "Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata) (3.21.0)\n",
            "Requirement already satisfied: shimmy in /usr/local/lib/python3.10/dist-packages (2.0.0)\n",
            "Requirement already satisfied: numpy>=1.18.0 in /usr/local/lib/python3.10/dist-packages (from shimmy) (1.26.4)\n",
            "Requirement already satisfied: gymnasium>=1.0.0a1 in /usr/local/lib/python3.10/dist-packages (from shimmy) (1.0.0)\n",
            "Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from gymnasium>=1.0.0a1->shimmy) (3.1.0)\n",
            "Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from gymnasium>=1.0.0a1->shimmy) (4.12.2)\n",
            "Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from gymnasium>=1.0.0a1->shimmy) (0.0.4)\n",
            "Collecting stable-baselines3[extra]\n",
            "  Using cached stable_baselines3-2.4.1-py3-none-any.whl.metadata (4.5 kB)\n",
            "Requirement already satisfied: gymnasium<1.1.0,>=0.29.1 in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (1.0.0)\n",
            "Requirement already satisfied: numpy<2.0,>=1.20 in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (1.26.4)\n",
            "Requirement already satisfied: torch>=1.13 in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (2.5.1+cu121)\n",
            "Requirement already satisfied: cloudpickle in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (3.1.0)\n",
            "Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (2.2.2)\n",
            "Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (3.10.0)\n",
            "Requirement already satisfied: opencv-python in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (4.10.0.84)\n",
            "Requirement already satisfied: pygame in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (2.6.1)\n",
            "Requirement already satisfied: tensorboard>=2.9.1 in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (2.17.1)\n",
            "Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (5.9.5)\n",
            "Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (4.67.1)\n",
            "Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (13.9.4)\n",
            "Collecting ale-py>=0.9.0 (from stable-baselines3[extra])\n",
            "  Using cached ale_py-0.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.6 kB)\n",
            "Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (11.1.0)\n",
            "Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from ale-py>=0.9.0->stable-baselines3[extra]) (4.12.2)\n",
            "Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from gymnasium<1.1.0,>=0.29.1->stable-baselines3[extra]) (0.0.4)\n",
            "Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.10/dist-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (1.4.0)\n",
            "Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.10/dist-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (1.69.0)\n",
            "Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (3.7)\n",
            "Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (24.2)\n",
            "Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /usr/local/lib/python3.10/dist-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (4.25.5)\n",
            "Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (75.1.0)\n",
            "Requirement already satisfied: six>1.9 in /usr/local/lib/python3.10/dist-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (1.17.0)\n",
            "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (0.7.2)\n",
            "Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (3.1.3)\n",
            "Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3[extra]) (3.16.1)\n",
            "Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3[extra]) (3.4.2)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3[extra]) (3.1.5)\n",
            "Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3[extra]) (2024.10.0)\n",
            "Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3[extra]) (1.13.1)\n",
            "Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch>=1.13->stable-baselines3[extra]) (1.3.0)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3[extra]) (1.3.1)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3[extra]) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3[extra]) (4.55.3)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3[extra]) (1.4.8)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3[extra]) (3.2.1)\n",
            "Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3[extra]) (2.8.2)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->stable-baselines3[extra]) (2024.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->stable-baselines3[extra]) (2024.2)\n",
            "Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->stable-baselines3[extra]) (3.0.0)\n",
            "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->stable-baselines3[extra]) (2.18.0)\n",
            "Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->stable-baselines3[extra]) (0.1.2)\n",
            "Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard>=2.9.1->stable-baselines3[extra]) (3.0.2)\n",
            "Using cached ale_py-0.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)\n",
            "Using cached stable_baselines3-2.4.1-py3-none-any.whl (183 kB)\n",
            "Installing collected packages: ale-py, stable-baselines3\n",
            "Successfully installed ale-py-0.10.1 stable-baselines3-2.4.1\n"
          ]
        }
      ],
      "source": [
        "!apt-get install -y \\\n",
        "    libgl1-mesa-dev \\\n",
        "    libgl1-mesa-glx \\\n",
        "    libglew-dev \\\n",
        "    libosmesa6-dev \\\n",
        "    software-properties-common\n",
        "\n",
        "!apt-get install -y patchelf\n",
        "\n",
        "!pip install gym\n",
        "!pip install free-mujoco-py\n",
        "!pip install importlib-metadata\n",
        "!pip install shimmy\n",
        "!pip install stable-baselines3[extra]"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Set up the custom Hopper environment and provided util functions\n",
        "\n",
        "\n",
        "\n",
        "1.   Upload `custom_hopper.zip` to the current session's file storage\n",
        "2.   Un-zip it by running cell below\n"
      ],
      "metadata": {
        "id": "gwIRXGd5K3xJ"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "os.chdir('project-sim2real-rialti-giunti-gjinaj/colab_template')\n",
        "!unzip custom_hopper.zip"
      ],
      "metadata": {
        "id": "T9WsofDVLaCC",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "3505bf7b-c51c-4e22-fb56-000b287c373d"
      },
      "execution_count": 6,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Archive:  custom_hopper.zip\n",
            "   creating: env/\n",
            "  inflating: env/__init__.py         \n",
            "  inflating: env/custom_hopper.py    \n",
            "  inflating: env/mujoco_env.py       \n",
            "   creating: env/assets/\n",
            "  inflating: env/assets/hopper.xml   \n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "\n",
        "\n",
        "---\n",
        "\n"
      ],
      "metadata": {
        "id": "7pJC_JevLf1f"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "\n",
        "**Test a random policy on the Gym Hopper environment**\n",
        "\n",
        "\\\n",
        "\n",
        "\n",
        "\n",
        "Play around with this code to get familiar with the\n",
        "Hopper environment.\n",
        "\n",
        "For example, what happens if you don't reset the environment\n",
        "even after the episode is over?\n",
        "When exactly is the episode over?\n",
        "What is an action here?"
      ],
      "metadata": {
        "id": "W4NsuF6pJPVJ"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import gym\n",
        "from env.custom_hopper import *"
      ],
      "metadata": {
        "id": "uTYmUufrJTNl",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "1cf8b1ef-888b-436d-8434-6e3fac7666d5"
      },
      "execution_count": 7,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.10/dist-packages/Cython/Distutils/old_build_ext.py:15: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.\n",
            "  from distutils.dep_util import newer, newer_group\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Compiling /usr/local/lib/python3.10/dist-packages/mujoco_py/cymj.pyx because it changed.\n",
            "[1/1] Cythonizing /usr/local/lib/python3.10/dist-packages/mujoco_py/cymj.pyx\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "INFO:root:running build_ext\n",
            "INFO:root:building 'mujoco_py.cymj' extension\n",
            "INFO:root:creating /usr/local/lib/python3.10/dist-packages/mujoco_py/generated/_pyxbld_2.0.2.13_310_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-310/usr/local/lib/python3.10/dist-packages/mujoco_py\n",
            "INFO:root:creating /usr/local/lib/python3.10/dist-packages/mujoco_py/generated/_pyxbld_2.0.2.13_310_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-310/usr/local/lib/python3.10/dist-packages/mujoco_py/gl\n",
            "INFO:root:x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.10/dist-packages/mujoco_py -I/usr/local/lib/python3.10/dist-packages/mujoco_py/binaries/linux/mujoco210/include -I/usr/local/lib/python3.10/dist-packages/numpy/core/include -I/usr/include/python3.10 -c /usr/local/lib/python3.10/dist-packages/mujoco_py/cymj.c -o /usr/local/lib/python3.10/dist-packages/mujoco_py/generated/_pyxbld_2.0.2.13_310_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-310/usr/local/lib/python3.10/dist-packages/mujoco_py/cymj.o -fopenmp -w\n",
            "INFO:root:x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.10/dist-packages/mujoco_py -I/usr/local/lib/python3.10/dist-packages/mujoco_py/binaries/linux/mujoco210/include -I/usr/local/lib/python3.10/dist-packages/numpy/core/include -I/usr/include/python3.10 -c /usr/local/lib/python3.10/dist-packages/mujoco_py/gl/osmesashim.c -o /usr/local/lib/python3.10/dist-packages/mujoco_py/generated/_pyxbld_2.0.2.13_310_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-310/usr/local/lib/python3.10/dist-packages/mujoco_py/gl/osmesashim.o -fopenmp -w\n",
            "INFO:root:creating /usr/local/lib/python3.10/dist-packages/mujoco_py/generated/_pyxbld_2.0.2.13_310_linuxcpuextensionbuilder/lib.linux-x86_64-cpython-310/mujoco_py\n",
            "INFO:root:x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 /usr/local/lib/python3.10/dist-packages/mujoco_py/generated/_pyxbld_2.0.2.13_310_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-310/usr/local/lib/python3.10/dist-packages/mujoco_py/cymj.o /usr/local/lib/python3.10/dist-packages/mujoco_py/generated/_pyxbld_2.0.2.13_310_linuxcpuextensionbuilder/temp.linux-x86_64-cpython-310/usr/local/lib/python3.10/dist-packages/mujoco_py/gl/osmesashim.o -L/usr/local/lib/python3.10/dist-packages/mujoco_py/binaries/linux/mujoco210/bin -L/usr/lib/x86_64-linux-gnu -Wl,--enable-new-dtags,-rpath,/usr/local/lib/python3.10/dist-packages/mujoco_py/binaries/linux/mujoco210/bin -lmujoco210 -lglewosmesa -lOSMesa -lGL -o /usr/local/lib/python3.10/dist-packages/mujoco_py/generated/_pyxbld_2.0.2.13_310_linuxcpuextensionbuilder/lib.linux-x86_64-cpython-310/mujoco_py/cymj.cpython-310-x86_64-linux-gnu.so -fopenmp\n",
            "<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "env = gym.make('CustomHopper-source-v0')\n",
        "# env = gym.make('CustomHopper-target-v0')\n",
        "print('State space:', env.observation_space)  # state-space\n",
        "print('Action space:', env.action_space)  # action-space\n",
        "print(\"Mass values of each link:\", env.model.body_mass)\n",
        "print('Dynamics parameters:', env.get_parameters())  # masses of each link of the Hopper\n",
        "print(\"Bodies defined in the environment:\", env.model.body_names)\n",
        "print(\"Number of degrees of freedom (DoFs) of the robot:\", env.model.nv)\n",
        "print(\"Number of DoFs for each body:\", env.model.body_dofnum)\n",
        "print(\"Number of actuators:\", env.model.nu)"
      ],
      "metadata": {
        "id": "QcCfCGg-Jyc3",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "a8c95e00-047c-45db-b1da-493b536e01c9"
      },
      "execution_count": 8,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "State space: Box(-inf, inf, (11,), float64)\n",
            "Action space: Box(-1.0, 1.0, (3,), float32)\n",
            "Mass values of each link: [0.         2.53429174 3.92699082 2.71433605 5.0893801 ]\n",
            "Dynamics parameters: [2.53429174 3.92699082 2.71433605 5.0893801 ]\n",
            "Bodies defined in the environment: ('world', 'torso', 'thigh', 'leg', 'foot')\n",
            "Number of degrees of freedom (DoFs) of the robot: 6\n",
            "Number of DoFs for each body: [0 3 1 1 1]\n",
            "Number of actuators: 3\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: \u001b[33mWARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.\u001b[0m\n",
            "  deprecation(\n",
            "/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: \u001b[33mWARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.\u001b[0m\n",
            "  deprecation(\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Analysis of the Hopper Environment in MuJoCo\n",
        "\n",
        "This document provides a detailed analysis of the Hopper environment based on the provided terminal output and information from the MuJoCo and Gym documentation.\n",
        "\n",
        "---\n",
        "\n",
        "## **Question 1.1: What is the state space in the Hopper environment? Is it discrete or continuous?**\n",
        "\n",
        "### **Answer:**\n",
        "- **State Space Description**:\n",
        "  The state space is represented by a **Box** object with shape `(11,)`, meaning it is a vector of 11 continuous values. These values typically include the positions, velocities, and potentially other sensory data (like contact forces) of the Hopper's components.\n",
        "  \n",
        "- **Nature of State Space**:\n",
        "  The state space is **continuous**, as indicated by the range `(-inf, inf)` and the use of the `Box` object.\n",
        "\n",
        "---\n",
        "\n",
        "## **Question 1.2: What is the action space in the Hopper environment? Is it discrete or continuous?**\n",
        "\n",
        "### **Answer:**\n",
        "- **Action Space Description**:\n",
        "  The action space is represented by a **Box** object with shape `(3,)`, meaning it consists of 3 continuous values. These correspond to the torques applied to the actuators controlling the Hopper's joints.\n",
        "\n",
        "- **Nature of Action Space**:\n",
        "  The action space is **continuous**, as indicated by the range `(-1.0, 1.0)` and the use of the `Box` object.\n",
        "\n",
        "---\n",
        "\n",
        "## **Question 1.3: What is the mass value of each link of the Hopper environment, in the source and target variants respectively?**\n",
        "\n",
        "### **Answer:**\n",
        "- **Mass Values for the Source Variant**:\n",
        "  From the terminal output:\n",
        "Mass values of each link: [0. 2.53429174 3.92699082 2.71433605 5.0893801 ]\n",
        "These correspond to the masses of the bodies:\n",
        "- `world`: 0.0 (fixed reference point)\n",
        "- `torso`: 2.5343\n",
        "- `thigh`: 3.9270\n",
        "- `leg`: 2.7143\n",
        "- `foot`: 5.0894\n",
        "\n",
        "- **Mass Values for the Target Variant**:\n",
        "The mass values for the target variant can be obtained by switching the environment initialization to:\n",
        "```python\n",
        "env = gym.make('CustomHopper-target-v0')\n",
        "(Ensure to re-run the relevant command to print the mass values.)\n",
        "\n",
        "Comparison of Source and Target Variants: Any differences in mass values between the source and target variants must be explicitly checked in the respective initialization. These differences typically simulate dynamics variability to test robustness.\n",
        "\n",
        "Additional Information Derived from the Environment\n",
        "Bodies Defined in the Environment:\n",
        "\n",
        "('world', 'torso', 'thigh', 'leg', 'foot')\n",
        "These represent the main components of the Hopper system.\n",
        "\n",
        "Number of Degrees of Freedom (DoFs) of the Robot: 6\n",
        "This includes translational and rotational movements of the robot.\n",
        "\n",
        "Number of DoFs for Each Body:\n",
        "[0 3 1 1 1]\n",
        "world: 0 (fixed body)\n",
        "torso: 3\n",
        "thigh: 1\n",
        "leg: 1\n",
        "foot: 1\n",
        "\n",
        "Number of Actuators:\n",
        "The Hopper has 3 actuators controlling its joints.\n",
        "\n",
        "Conclusion\n",
        "\n",
        "The Hopper environment features a continuous state and action space, making it well-suited for reinforcement learning tasks. Understanding the dynamics, including body masses and degrees of freedom, is crucial for designing robust controllers and algorithms."
      ],
      "metadata": {
        "id": "AYhXnui3h70A"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "n_episodes = 5\n",
        "\n",
        "for episode in range(n_episodes):\n",
        "  done = False\n",
        "  observation = env.reset()\t # Reset environment to initial state\n",
        "\n",
        "  while not done:  # Until the episode is over\n",
        "\n",
        "    action = env.action_space.sample()\t# Sample random action\n",
        "\n",
        "    observation, reward, done, info = env.step(action)\t# Step the simulator to the next timestep"
      ],
      "metadata": {
        "id": "DT1oXr8HJ05h",
        "outputId": "72564f54-b0a8-4f0e-c039-0b1363f0a820",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "execution_count": 9,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:174: UserWarning: \u001b[33mWARN: Future gym versions will require that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.\u001b[0m\n",
            "  logger.warn(\n",
            "/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:190: UserWarning: \u001b[33mWARN: Future gym versions will require that `Env.reset` can be passed `return_info` to return information from the environment resetting.\u001b[0m\n",
            "  logger.warn(\n",
            "/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:195: UserWarning: \u001b[33mWARN: Future gym versions will require that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.\u001b[0m\n",
            "  logger.warn(\n",
            "/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:227: DeprecationWarning: \u001b[33mWARN: Core environment is written in old step API which returns one bool instead of two. It is recommended to rewrite the environment with new step API. \u001b[0m\n",
            "  logger.deprecation(\n",
            "/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)\n",
            "  if not isinstance(done, (bool, np.bool8)):\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "! python  /content/project-sim2real-rialti-giunti-gjinaj/trainTest.py --model_name sac_hopper --total_timesteps 1000"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "XKi913Qgj2xI",
        "outputId": "7157c032-e330-47a4-d4d9-a1c69e66b27a"
      },
      "execution_count": 22,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "/usr/local/lib/python3.10/dist-packages/Cython/Distutils/old_build_ext.py:15: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.\n",
            "  from distutils.dep_util import newer, newer_group\n",
            "<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead\n",
            "2025-01-10 09:53:29.347729: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "2025-01-10 09:53:29.372279: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "2025-01-10 09:53:29.379834: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "2025-01-10 09:53:29.398379: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2025-01-10 09:53:30.841530: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
            "/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/util.py:55: DeprecationWarning: jax.xla_computation is deprecated. Please use the AOT APIs; see https://jax.readthedocs.io/en/latest/aot.html. For example, replace xla_computation(f)(*xs) with jit(f).lower(*xs).compiler_ir('hlo'). See CHANGELOG.md for 0.4.30 for more examples.\n",
            "  from jax import xla_computation as _xla_computation\n",
            "/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: \u001b[33mWARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.\u001b[0m\n",
            "  deprecation(\n",
            "/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: \u001b[33mWARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.\u001b[0m\n",
            "  deprecation(\n",
            "Using cpu device\n",
            "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/vec_env/patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.\n",
            "  warnings.warn(\n",
            "Wrapping the env with a `Monitor` wrapper\n",
            "Wrapping the env in a DummyVecEnv.\n",
            "/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: \u001b[33mWARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.\u001b[0m\n",
            "  deprecation(\n",
            "/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: \u001b[33mWARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.\u001b[0m\n",
            "  deprecation(\n",
            "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/vec_env/patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.\n",
            "  warnings.warn(\n",
            "/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:174: UserWarning: \u001b[33mWARN: Future gym versions will require that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.\u001b[0m\n",
            "  logger.warn(\n",
            "/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:190: UserWarning: \u001b[33mWARN: Future gym versions will require that `Env.reset` can be passed `return_info` to return information from the environment resetting.\u001b[0m\n",
            "  logger.warn(\n",
            "/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:195: UserWarning: \u001b[33mWARN: Future gym versions will require that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.\u001b[0m\n",
            "  logger.warn(\n",
            "/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:227: DeprecationWarning: \u001b[33mWARN: Core environment is written in old step API which returns one bool instead of two. It is recommended to rewrite the environment with new step API. \u001b[0m\n",
            "  logger.deprecation(\n",
            "/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)\n",
            "  if not isinstance(done, (bool, np.bool8)):\n",
            "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.\n",
            "  warnings.warn(\n",
            "Eval num_timesteps=50, episode_reward=17.74 +/- 0.23\n",
            "Episode length: 34.80 +/- 0.75\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 34.8     |\n",
            "|    mean_reward     | 17.7     |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 50       |\n",
            "---------------------------------\n",
            "New best mean reward!\n",
            "---------------------------------\n",
            "| rollout/           |          |\n",
            "|    ep_len_mean     | 23.2     |\n",
            "|    ep_rew_mean     | 13.8     |\n",
            "| time/              |          |\n",
            "|    episodes        | 4        |\n",
            "|    fps             | 253      |\n",
            "|    time_elapsed    | 0        |\n",
            "|    total_timesteps | 93       |\n",
            "---------------------------------\n",
            "Eval num_timesteps=100, episode_reward=17.85 +/- 0.17\n",
            "Episode length: 35.00 +/- 0.63\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 35       |\n",
            "|    mean_reward     | 17.8     |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 100      |\n",
            "---------------------------------\n",
            "New best mean reward!\n",
            "Eval num_timesteps=150, episode_reward=35.56 +/- 0.25\n",
            "Episode length: 41.60 +/- 0.49\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 41.6     |\n",
            "|    mean_reward     | 35.6     |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 150      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -4.55    |\n",
            "|    critic_loss     | 0.975    |\n",
            "|    ent_coef        | 0.986    |\n",
            "|    ent_coef_loss   | -0.0727  |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 49       |\n",
            "---------------------------------\n",
            "New best mean reward!\n",
            "---------------------------------\n",
            "| rollout/           |          |\n",
            "|    ep_len_mean     | 20.9     |\n",
            "|    ep_rew_mean     | 13.4     |\n",
            "| time/              |          |\n",
            "|    episodes        | 8        |\n",
            "|    fps             | 59       |\n",
            "|    time_elapsed    | 2        |\n",
            "|    total_timesteps | 167      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -4.63    |\n",
            "|    critic_loss     | 0.99     |\n",
            "|    ent_coef        | 0.981    |\n",
            "|    ent_coef_loss   | -0.0979  |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 66       |\n",
            "---------------------------------\n",
            "Eval num_timesteps=200, episode_reward=17.38 +/- 0.19\n",
            "Episode length: 29.40 +/- 0.49\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 29.4     |\n",
            "|    mean_reward     | 17.4     |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 200      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -4.99    |\n",
            "|    critic_loss     | 0.652    |\n",
            "|    ent_coef        | 0.971    |\n",
            "|    ent_coef_loss   | -0.148   |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 99       |\n",
            "---------------------------------\n",
            "Eval num_timesteps=250, episode_reward=29.30 +/- 0.33\n",
            "Episode length: 39.60 +/- 0.49\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 39.6     |\n",
            "|    mean_reward     | 29.3     |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 250      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -5.44    |\n",
            "|    critic_loss     | 0.467    |\n",
            "|    ent_coef        | 0.957    |\n",
            "|    ent_coef_loss   | -0.223   |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 149      |\n",
            "---------------------------------\n",
            "---------------------------------\n",
            "| rollout/           |          |\n",
            "|    ep_len_mean     | 22.1     |\n",
            "|    ep_rew_mean     | 13.7     |\n",
            "| time/              |          |\n",
            "|    episodes        | 12       |\n",
            "|    fps             | 44       |\n",
            "|    time_elapsed    | 5        |\n",
            "|    total_timesteps | 265      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -5.48    |\n",
            "|    critic_loss     | 0.413    |\n",
            "|    ent_coef        | 0.952    |\n",
            "|    ent_coef_loss   | -0.245   |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 164      |\n",
            "---------------------------------\n",
            "Eval num_timesteps=300, episode_reward=32.40 +/- 0.83\n",
            "Episode length: 61.40 +/- 1.62\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 61.4     |\n",
            "|    mean_reward     | 32.4     |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 300      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -5.73    |\n",
            "|    critic_loss     | 0.526    |\n",
            "|    ent_coef        | 0.942    |\n",
            "|    ent_coef_loss   | -0.301   |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 199      |\n",
            "---------------------------------\n",
            "---------------------------------\n",
            "| rollout/           |          |\n",
            "|    ep_len_mean     | 21.1     |\n",
            "|    ep_rew_mean     | 13.4     |\n",
            "| time/              |          |\n",
            "|    episodes        | 16       |\n",
            "|    fps             | 40       |\n",
            "|    time_elapsed    | 8        |\n",
            "|    total_timesteps | 338      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -6.15    |\n",
            "|    critic_loss     | 0.454    |\n",
            "|    ent_coef        | 0.932    |\n",
            "|    ent_coef_loss   | -0.355   |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 237      |\n",
            "---------------------------------\n",
            "Eval num_timesteps=350, episode_reward=26.68 +/- 0.29\n",
            "Episode length: 56.00 +/- 0.63\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 56       |\n",
            "|    mean_reward     | 26.7     |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 350      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -6.26    |\n",
            "|    critic_loss     | 0.367    |\n",
            "|    ent_coef        | 0.928    |\n",
            "|    ent_coef_loss   | -0.375   |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 249      |\n",
            "---------------------------------\n",
            "Eval num_timesteps=400, episode_reward=18.24 +/- 0.27\n",
            "Episode length: 47.00 +/- 0.63\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 47       |\n",
            "|    mean_reward     | 18.2     |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 400      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -6.54    |\n",
            "|    critic_loss     | 0.552    |\n",
            "|    ent_coef        | 0.915    |\n",
            "|    ent_coef_loss   | -0.446   |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 299      |\n",
            "---------------------------------\n",
            "---------------------------------\n",
            "| rollout/           |          |\n",
            "|    ep_len_mean     | 21.7     |\n",
            "|    ep_rew_mean     | 14.4     |\n",
            "| time/              |          |\n",
            "|    episodes        | 20       |\n",
            "|    fps             | 35       |\n",
            "|    time_elapsed    | 12       |\n",
            "|    total_timesteps | 434      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -6.8     |\n",
            "|    critic_loss     | 0.637    |\n",
            "|    ent_coef        | 0.905    |\n",
            "|    ent_coef_loss   | -0.497   |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 333      |\n",
            "---------------------------------\n",
            "Eval num_timesteps=450, episode_reward=34.97 +/- 1.62\n",
            "Episode length: 64.00 +/- 2.28\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 64       |\n",
            "|    mean_reward     | 35       |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 450      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -6.95    |\n",
            "|    critic_loss     | 0.523    |\n",
            "|    ent_coef        | 0.901    |\n",
            "|    ent_coef_loss   | -0.525   |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 349      |\n",
            "---------------------------------\n",
            "Eval num_timesteps=500, episode_reward=36.67 +/- 0.56\n",
            "Episode length: 65.40 +/- 1.02\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 65.4     |\n",
            "|    mean_reward     | 36.7     |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 500      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -7.2     |\n",
            "|    critic_loss     | 0.678    |\n",
            "|    ent_coef        | 0.888    |\n",
            "|    ent_coef_loss   | -0.599   |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 399      |\n",
            "---------------------------------\n",
            "New best mean reward!\n",
            "Eval num_timesteps=550, episode_reward=50.05 +/- 1.92\n",
            "Episode length: 78.80 +/- 1.94\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 78.8     |\n",
            "|    mean_reward     | 50.1     |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 550      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -8.09    |\n",
            "|    critic_loss     | 0.36     |\n",
            "|    ent_coef        | 0.874    |\n",
            "|    ent_coef_loss   | -0.666   |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 449      |\n",
            "---------------------------------\n",
            "New best mean reward!\n",
            "Eval num_timesteps=600, episode_reward=21.45 +/- 0.11\n",
            "Episode length: 50.20 +/- 0.75\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 50.2     |\n",
            "|    mean_reward     | 21.5     |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 600      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -8.44    |\n",
            "|    critic_loss     | 0.449    |\n",
            "|    ent_coef        | 0.861    |\n",
            "|    ent_coef_loss   | -0.743   |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 499      |\n",
            "---------------------------------\n",
            "---------------------------------\n",
            "| rollout/           |          |\n",
            "|    ep_len_mean     | 25.7     |\n",
            "|    ep_rew_mean     | 22.2     |\n",
            "| time/              |          |\n",
            "|    episodes        | 24       |\n",
            "|    fps             | 27       |\n",
            "|    time_elapsed    | 22       |\n",
            "|    total_timesteps | 616      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -8.45    |\n",
            "|    critic_loss     | 0.479    |\n",
            "|    ent_coef        | 0.857    |\n",
            "|    ent_coef_loss   | -0.771   |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 515      |\n",
            "---------------------------------\n",
            "Eval num_timesteps=650, episode_reward=18.24 +/- 0.13\n",
            "Episode length: 47.60 +/- 0.80\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 47.6     |\n",
            "|    mean_reward     | 18.2     |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 650      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -9.04    |\n",
            "|    critic_loss     | 1.37     |\n",
            "|    ent_coef        | 0.849    |\n",
            "|    ent_coef_loss   | -0.81    |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 549      |\n",
            "---------------------------------\n",
            "Eval num_timesteps=700, episode_reward=16.44 +/- 0.23\n",
            "Episode length: 45.60 +/- 0.49\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 45.6     |\n",
            "|    mean_reward     | 16.4     |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 700      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -9.46    |\n",
            "|    critic_loss     | 0.854    |\n",
            "|    ent_coef        | 0.836    |\n",
            "|    ent_coef_loss   | -0.883   |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 599      |\n",
            "---------------------------------\n",
            "---------------------------------\n",
            "| rollout/           |          |\n",
            "|    ep_len_mean     | 26.2     |\n",
            "|    ep_rew_mean     | 23.1     |\n",
            "| time/              |          |\n",
            "|    episodes        | 28       |\n",
            "|    fps             | 27       |\n",
            "|    time_elapsed    | 27       |\n",
            "|    total_timesteps | 734      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -9.65    |\n",
            "|    critic_loss     | 1.13     |\n",
            "|    ent_coef        | 0.828    |\n",
            "|    ent_coef_loss   | -0.934   |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 633      |\n",
            "---------------------------------\n",
            "Eval num_timesteps=750, episode_reward=15.34 +/- 0.32\n",
            "Episode length: 44.80 +/- 0.40\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 44.8     |\n",
            "|    mean_reward     | 15.3     |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 750      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -9.86    |\n",
            "|    critic_loss     | 1.11     |\n",
            "|    ent_coef        | 0.824    |\n",
            "|    ent_coef_loss   | -0.943   |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 649      |\n",
            "---------------------------------\n",
            "Eval num_timesteps=800, episode_reward=35.99 +/- 0.91\n",
            "Episode length: 65.20 +/- 1.17\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 65.2     |\n",
            "|    mean_reward     | 36       |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 800      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -10.2    |\n",
            "|    critic_loss     | 1.2      |\n",
            "|    ent_coef        | 0.812    |\n",
            "|    ent_coef_loss   | -1.02    |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 699      |\n",
            "---------------------------------\n",
            "Eval num_timesteps=850, episode_reward=76.89 +/- 5.12\n",
            "Episode length: 106.00 +/- 5.76\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 106      |\n",
            "|    mean_reward     | 76.9     |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 850      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -10.9    |\n",
            "|    critic_loss     | 0.801    |\n",
            "|    ent_coef        | 0.8      |\n",
            "|    ent_coef_loss   | -1.09    |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 749      |\n",
            "---------------------------------\n",
            "New best mean reward!\n",
            "Eval num_timesteps=900, episode_reward=84.30 +/- 2.51\n",
            "Episode length: 55.40 +/- 1.62\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 55.4     |\n",
            "|    mean_reward     | 84.3     |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 900      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -11.3    |\n",
            "|    critic_loss     | 0.799    |\n",
            "|    ent_coef        | 0.789    |\n",
            "|    ent_coef_loss   | -1.15    |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 799      |\n",
            "---------------------------------\n",
            "New best mean reward!\n",
            "Eval num_timesteps=950, episode_reward=72.52 +/- 1.43\n",
            "Episode length: 44.00 +/- 0.63\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 44       |\n",
            "|    mean_reward     | 72.5     |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 950      |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -11.4    |\n",
            "|    critic_loss     | 0.642    |\n",
            "|    ent_coef        | 0.777    |\n",
            "|    ent_coef_loss   | -1.2     |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 849      |\n",
            "---------------------------------\n",
            "Eval num_timesteps=1000, episode_reward=59.75 +/- 0.91\n",
            "Episode length: 35.20 +/- 0.40\n",
            "---------------------------------\n",
            "| eval/              |          |\n",
            "|    mean_ep_length  | 35.2     |\n",
            "|    mean_reward     | 59.7     |\n",
            "| time/              |          |\n",
            "|    total_timesteps | 1000     |\n",
            "| train/             |          |\n",
            "|    actor_loss      | -11.8    |\n",
            "|    critic_loss     | 0.704    |\n",
            "|    ent_coef        | 0.766    |\n",
            "|    ent_coef_loss   | -1.25    |\n",
            "|    learning_rate   | 0.0003   |\n",
            "|    n_updates       | 899      |\n",
            "---------------------------------\n",
            "Modello salvato come ./sim2real/models/sac_hopper.zip\n",
            "/usr/local/lib/python3.10/dist-packages/jupyter_client/connect.py:28: DeprecationWarning: Jupyter is migrating its paths to use standard platformdirs\n",
            "given by the platformdirs library.  To remove this warning and\n",
            "see the appropriate new directories, set the environment variable\n",
            "`JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.\n",
            "The use of platformdirs will be the default in `jupyter_core` v6\n",
            "  from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write\n",
            "Figure(640x480)\n",
            "Grafico delle ricompense salvato in ./sim2real/plots/rewards_plot.png\n",
            "State space: Box(-inf, inf, (11,), float64)\n",
            "Action space: Box(-1.0, 1.0, (3,), float32)\n",
            "Dynamics parameters: [2.53429174 3.92699082 2.71433605 5.0893801 ]\n"
          ]
        }
      ]
    }
  ]
}